### Получение всех элементов
GET http://localhost:8080/books


### Получение 1 элемента по id
GET http://localhost:8080/books/2


### Добавление нового элемента
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "IT",
  "authorId": 1
}


### Обновление элемента
PATCH http://localhost:8080/books/2
Content-Type: application/json

{
  "title": "IT work",
  "authorId": 2
}


### Удаление элемента
DELETE http://localhost:8080/books/3