spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: ENC(IJKesAtE+2D9RPoQ7kFrwuPN8BknkQqnVq59fDphZFnSeylddTEfuUwDO7RKHLNY)
    hikari:
      schema: test
      minimum-idle: 2
      maximum-pool-size: 4
      idle-timeout: 200000
      max-lifetime: 900000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        default_schema: test
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    enabled: true
    url: /api-docs




